### ISSUE TITLE
MacOS?

### ISSUE THREAD

**Issue by Butterscotch-P1e** [ItzBlinkzy/roblox-rpc#13]
MacOS support

**Comment by ItzBlinkzy** [comment]
Already supported, though it may be still a little buggy, feel free to re-open an issue if there are any specific issues with MacOS.

**Comment by Butterscotch-P1e** [comment]
There’s no Mac downloadOn Nov 3, 2024, at 9:51 AM, Blinkzy ***@***.***> wrote:﻿
Already supported, though it may be still a little buggy, feel free to re-open an issue if there are any specific issues with MacOS.

**Comment by Kataokax1** [comment]
Where is the mac download?
