### ISSUE TITLE
The application does not work for me

### ISSUE THREAD

**Issue by ArmorKeik** [ItzBlinkzy/roblox-rpc#2]
Hello, at the moment I only tested in one game and the rich presence does not appear in Discord.

I am currently playing: https://www.roblox.com/games/8216196965/Touch-Soccer-League

I followed all the steps for the installation and already verified my account.

![image](https://user-images.githubusercontent.com/87909542/208966076-e6378b2f-89bc-4589-bb11-52ddfb0aeb19.png)

![image](https://user-images.githubusercontent.com/87909542/208964907-824efbe7-3508-4177-9893-a1c8e0a78e70.png)

![image](https://user-images.githubusercontent.com/87909542/208965133-5be60336-8d49-4d41-8d48-a006728616ff.png)

**Comment by ItzBlinkzy** [comment]
Yes, the bot cookie that tracks everyone games expired I will be replacing it with a new one and sending out the new release. In the next 10 mins

**Comment by ItzBlinkzy** [comment]
I will keep you updated.

**Comment by ItzBlinkzy** [comment]
Hello, I've created a new [release](https://github.com/ItzBlinkzy/roblox-rpc/releases) version `v1.5.4`. 
This fixes the problem you had and some other smaller issues.

**Comment by ItzBlinkzy** [comment]
Feel free to open another issue, if you have any more problems.

**Comment by lucretiaa** [comment]
Doesn't detect anything for me as of now and I verified as well + followed the RPC account + fixed join settings, is this on Roblox's side?
