### ISSUE TITLE
Built

### ISSUE THREAD

**Issue by sarayuuki** [ItzBlinkzy/roblox-rpc#3]
So i built the program from source, but it throws an error of a unexpected whitespace character. what do i do?

**Comment by ItzBlinkzy** [comment]
Hello, are you able to provide more specifics of the version you are using as well as the exact error you are getting, such as a screenshot of the error.
Thanks.

**Comment by ItzBlinkzy** [comment]
Resolved in Discord DM's (9a547cf)
