### ISSUE TITLE
Game not detecting

### ISSUE THREAD

**Issue by cirrens** [ItzBlinkzy/roblox-rpc#4]
Not sure what to do, followed the RPC account + fixed join settings. Also verified. Is this on Roblox's side? I know their constant updates would break a lot of stuff.

I extracted the .zip file and ran the application but interestingly there was no setup to do.

Appeared in my system tray and ran multiple processes in the background, but when I clicked/right-clicked, nothing appeared.

If it helps I'm on Windows 11.

**Comment by ItzBlinkzy** [comment]
Hello, I recently had to update the internal API wrapper I was using to access ROBLOX API, the code is updated however I never released the new version of the executable after this commit (9a547cf ) so all previous versions no longer work. I will get back to you later today when I release this version, thanks for notifying.

**Comment by ikwhattoput** [comment]
im having the same problem too i cant click the system tray icon and nothing happens ( i need to close it using task manager) i am using windows 11

**Comment by ItzBlinkzy** [comment]
V2 is released [ROBLOX RPC V2](https://github.com/ItzBlinkzy/roblox-rpc/releases/tag/v2.0.0)
Should work fine now.
