### ISSUE TITLE
Update status?

### ISSUE THREAD

**Issue by oilbirb** [ItzBlinkzy/roblox-rpc#6]
Hello! I was trying to use roblox-rpc for like 10 minutes realizing it isn't working(for me at least)..Do you know when it will run again? If not is there a guide to make it work on windows 11 or is it discontinued?

**Comment by ItzBlinkzy** [comment]
I am currently in the process of a big update that will ensure roblox-rpc works permanently, this may take 1-2 weeks, but roblox-rpc is not discontinued yet.

**Comment by ItzBlinkzy** [comment]
I've released [ROBLOX RPC V2](https://github.com/ItzBlinkzy/roblox-rpc/releases/tag/v2.0.0) and it should be working fine on Windows 10 and 11
If you come across any issues with v2 don't hesitate to create another issue or ask in the [Discord Server](https://discord.com/invite/aq9rwUCQrK).
