### ISSUE TITLE
README has an invalid discord invite

### ISSUE THREAD

**Issue by RealmKebab** [ItzBlinkzy/roblox-rpc#8]
the invite link isn't even valid, it just says "discord.gg/invite" nothing else
found [here](https://github.com/ItzBlinkzy/roblox-rpc#how-to-use)

**Comment by ItzBlinkzy** [comment]
Apologies I missed that, here is the [server](https://discord.com/invite/aq9rwUCQrK). Please note there is a crucial limitation with how roblox handle's cookies and IP's and I'm currently working on a fix, so as of now. V2 does not work unless you live in the same geographical location as me (Ireland)
